"""QSS builder: generates the application stylesheet from design tokens.

Global element rules live here (single source of truth). objectName/property
rules that belong to specific screens are kept in the transitional
``resources/ui/themes/legacy-dark.qss`` extras file until those screens migrate;
``scripts/scrs/build_theme.py`` assembles the deployed artifact.

Rules of the road:
- No raw hex/rgba literals in widgets; widgets set properties, this builder
  turns tokens into QSS.
- Every interactive control defines default/hover/pressed/focus/disabled
  (+selected/checked where applicable).
"""
from __future__ import annotations

from palworld_aio.ui.chrome import fonts
from palworld_aio.ui.chrome.fonts import (
    FONT_BODY_STACK, FONT_HEADING_STACK, FONT_ICON_STACK, FONT_MONO_STACK,
    font_family_qss,
)
from palworld_aio.ui.chrome.tokens import HEIGHT, RADIUS, SPACING, TYPE, resolve

BUTTON_PAD = f'{SPACING["sm"] - 2}px {SPACING["lg"] - 2}px'


def _font_rule(selector: str, stack: list[str], px: int) -> str:
    return (f'{selector} {{\n'
            f'    font-family: {fonts.font_family_qss(stack)};\n'
            f'    font-size: {px}px;\n}}\n')


def build_qss(theme: str = 'dark') -> str:
    p = resolve(theme)
    d = TYPE['display']
    return f"""
/* ==== PalTrainer application stylesheet — generated by qss_builder. ====
   Do not edit the deployed .qss by hand; edit tokens/qss_builder and run
   scripts/scrs/build_theme.py. */

/* ---- canvas & default text ---- */
QWidget#central {{
    background-color: {p['canvas']};
    color: {p['text']};
    font-family: {fonts.font_family_qss(fonts.FONT_BODY_STACK)};
}}
QLabel {{
    color: {p['text']};
    background: transparent;
}}
QLabel[role="secondary"] {{ color: {p['text_secondary']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel[role="muted"] {{ color: {p['text_disabled']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel[role="accent"] {{ color: {p['accent']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel[role="success"] {{ color: {p['success']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel[role="warning"] {{ color: {p['warning']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel[role="danger"] {{ color: {p['danger']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel[role="mono"] {{ font-family: {fonts.font_family_qss(fonts.FONT_MONO_STACK)}; }}

QStackedWidget {{
    background: transparent;
    border: none;
    padding: 0px;
    margin: 0px;
    color: {p['text']};
}}
QStackedWidget > QWidget {{
    background: transparent;
    color: {p['text']};
}}
QScrollArea {{
    border: none;
    background: transparent;
    border-radius: {RADIUS['lg']}px;
}}
/* Inner scroll containers must not fall back to the light default palette
   (Breeding results rendered as a white rectangle without this rule). */
QScrollArea > QWidget > QWidget {{
    background: transparent;
}}

/* ---- inputs ---- */
QLineEdit, QSpinBox, QDoubleSpinBox, QTextEdit, QPlainTextEdit {{
    background-color: {p['surface_input']};
    color: {p['text']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    padding: 5px 10px;
    selection-background-color: {p['accent_bg_strong']};
    selection-color: {p['text']};
}}
QLineEdit:focus, QSpinBox:focus, QDoubleSpinBox:focus,
QTextEdit:focus, QPlainTextEdit:focus {{
    border: 1px solid {p['accent_border_strong']};
}}
QLineEdit:hover, QSpinBox:hover, QDoubleSpinBox:hover {{
    border-color: {p['border_strong']};
}}
QLineEdit:disabled, QSpinBox:disabled, QDoubleSpinBox:disabled,
QTextEdit:disabled, QPlainTextEdit:disabled {{
    background-color: {p['surface']};
    color: {p['text_disabled']};
    border-color: {p['border']};
}}
QLineEdit[error="true"], QSpinBox[error="true"], QDoubleSpinBox[error="true"] {{
    border: 1px solid {p['danger_border']};
    background-color: {p['danger_bg']};
}}
QLineEdit[error="true"]:focus {{ border: 1px solid {p['danger']}; }}

QComboBox {{
    background-color: {p['surface_input']};
    color: {p['text']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    padding: 4px 8px;
    min-height: {HEIGHT['default'] - 10}px;
}}
QComboBox:hover {{ border-color: {p['border_strong']}; }}
QComboBox:focus {{ border-color: {p['accent_border_strong']}; }}
QComboBox:disabled {{ background-color: {p['surface']}; color: {p['text_disabled']}; }}
QComboBox::drop-down {{ border: none; width: 20px; }}
QComboBox::down-arrow {{
    width: 0; height: 0;
    border-left: 4px solid transparent;
    border-right: 4px solid transparent;
    border-top: 5px solid {p['text_secondary']};
    margin-right: 6px;
}}
QComboBox::down-arrow:hover {{ border-top-color: {p['text']}; }}
QComboBox QAbstractItemView {{
    background-color: {p['surface_raised']};
    color: {p['text']};
    border: 1px solid {p['border_strong']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['xs']}px;
    selection-background-color: {p['accent_bg_strong']};
    selection-color: {p['text']};
    outline: none;
}}
QComboBox QAbstractItemView::item {{
    padding: 4px 10px;
    border-radius: {RADIUS['sm']}px;
    min-height: {HEIGHT['compact']}px;
}}
QSpinBox::up-button, QSpinBox::down-button {{
    background: {p['surface_raised']};
    border: none;
    width: 16px;
}}
QSpinBox::up-button:hover, QSpinBox::down-button:hover {{ background: {p['surface_hover']}; }}
QSpinBox::up-arrow {{
    width: 0; height: 0;
    border-left: 3px solid transparent;
    border-right: 3px solid transparent;
    border-bottom: 4px solid {p['text_secondary']};
}}
QSpinBox::down-arrow {{
    width: 0; height: 0;
    border-left: 3px solid transparent;
    border-right: 3px solid transparent;
    border-top: 4px solid {p['text_secondary']};
}}

/* ---- buttons ---- */
QPushButton {{
    background-color: {p['surface_raised']};
    color: {p['text']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: {BUTTON_PAD};
    font-weight: 600;
}}
QPushButton:hover {{
    background-color: {p['surface_hover']};
    border-color: {p['border_strong']};
}}
QPushButton:pressed {{
    background-color: {p['surface_input']};
}}
QPushButton:focus {{
    border: 1px solid {p['accent_border_strong']};
}}
QPushButton:disabled {{
    background-color: {p['surface']};
    color: {p['text_disabled']};
    border-color: {p['border']};
}}
QPushButton[class="primary"] {{
    background-color: {p['accent']};
    color: {p['text_on_accent']};
    border: 1px solid {p['accent']};
    padding: {BUTTON_PAD};
    min-height: {HEIGHT['cta'] - 28}px;
}}
QPushButton[class="primary"]:hover {{
    background-color: {p['accent_hover']};
    border-color: {p['accent_hover']};
}}
QPushButton[class="primary"]:pressed {{ background-color: {p['accent_pressed']}; }}
QPushButton[class="primary"]:focus {{ border: 1px solid {p['text']}; }}
QPushButton[class="primary"]:disabled {{
    background-color: {p['surface_raised']};
    color: {p['text_disabled']};
    border-color: {p['border']};
}}
QPushButton[class="danger"] {{
    background-color: {p['danger_bg']};
    color: {p['danger']};
    border: 1px solid {p['danger_border']};
}}
QPushButton[class="danger"]:hover {{
    background-color: {p['danger_bg']};
    border-color: {p['danger']};
}}
QPushButton[class="danger"]:pressed {{ background-color: {p['danger_border']}; }}
QPushButton[class="danger"]:disabled {{
    background-color: {p['surface']};
    color: {p['text_disabled']};
    border-color: {p['border']};
}}
QPushButton[class="ghost"] {{
    background: transparent;
    color: {p['text_secondary']};
    border: 1px solid transparent;
}}
QPushButton[class="ghost"]:hover {{
    background-color: {p['surface_hover']};
    color: {p['text']};
}}
QPushButton[class="ghost"]:pressed {{ background-color: {p['surface_active']}; }}
QPushButton[class="ghost"]:disabled {{ color: {p['text_disabled']}; background: transparent; }}
QPushButton[class="tool"] {{
    background: transparent;
    color: {p['text_secondary']};
    border: 1px solid transparent;
    padding: {SPACING['xs']}px;
}}
QPushButton[class="tool"]:hover {{
    background-color: {p['surface_hover']};
    color: {p['text']};
    border-radius: {RADIUS['md']}px;
}}
QPushButton[class="tool"]:pressed {{ background-color: {p['surface_active']}; }}
QPushButton[class="tool"]:checked {{
    background-color: {p['surface_active']};
    color: {p['accent']};
    border-color: {p['accent_border']};
}}
QPushButton[class="tool"]:disabled {{ color: {p['text_disabled']}; }}

/* ---- selection views ---- */
QTreeWidget, QTreeView, QListWidget, QTableWidget, QTableView, QListView {{
    background: transparent;
    color: {p['text']};
    border: 1px solid transparent;
    border-radius: {RADIUS['md']}px;
    outline: none;
    alternate-background-color: {p['surface']};
}}
QTreeWidget:focus, QTreeView:focus, QListWidget:focus,
QTableWidget:focus, QTableView:focus, QListView:focus {{
    border: 1px solid {p['accent_border']};
}}
QTreeWidget::item, QTreeView::item, QListWidget::item,
QListView::item, QTableWidget::item, QTableView::item {{
    padding: 4px 8px;
    border-radius: {RADIUS['sm']}px;
    color: {p['text']};
}}
QTreeWidget::item:hover, QTreeView::item:hover, QListWidget::item:hover,
QListView::item:hover {{
    background: {p['surface_hover']};
}}
QTreeWidget::item:selected, QTreeView::item:selected, QListWidget::item:selected,
QListView::item:selected {{
    background: {p['accent_bg_strong']};
    color: {p['text']};
}}
QTreeWidget::item:selected:!active, QTreeView::item:selected:!active,
QListWidget::item:selected:!active, QListView::item:selected:!active {{
    background: {p['accent_bg']};
}}
QTableWidget::item:selected, QTableView::item:selected {{
    background: {p['accent_bg_strong']};
    color: {p['text']};
}}
QHeaderView {{ background: transparent; border: none; }}
QHeaderView::section {{
    background-color: {p['surface']};
    color: {p['text_secondary']};
    padding: 6px 8px;
    border: none;
    border-bottom: 1px solid {p['border']};
    border-right: 1px solid {p['border']};
    height: {HEIGHT['default']}px;
    font-size: {TYPE['secondary'][0]}px;
    font-weight: 600;
}}
QHeaderView::section:hover {{ background-color: {p['surface_raised']}; }}
QHeaderView::section:last {{ border-right: none; }}

/* ---- feedback & chrome ---- */
QProgressBar {{
    background: {p['surface_input']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    height: 12px;
    text-align: center;
    color: {p['text_secondary']};
    font-size: {TYPE['micro'][0]}px;
}}
QProgressBar::chunk {{
    background: {p['accent']};
    border-radius: {RADIUS['sm'] - 1}px;
}}
QCheckBox, QRadioButton {{
    color: {p['text']};
    spacing: {SPACING['sm']}px;
    background: transparent;
}}
QCheckBox::indicator, QRadioButton::indicator {{
    width: 16px; height: 16px;
    border: 1px solid {p['border_strong']};
    background: {p['surface_input']};
}}
QCheckBox::indicator {{ border-radius: {RADIUS['sm']}px; }}
QRadioButton::indicator {{ border-radius: 8px; }}
QCheckBox::indicator:hover, QRadioButton::indicator:hover {{
    border-color: {p['accent_border']};
}}
QCheckBox::indicator:checked, QRadioButton::indicator:checked {{
    background-color: {p['accent']};
    border-color: {p['accent']};
}}
QCheckBox::indicator:disabled, QRadioButton::indicator:disabled {{
    background: {p['surface']};
    border-color: {p['border']};
}}
QGroupBox {{
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    margin-top: 10px;
    color: {p['text_secondary']};
    font-weight: 600;
}}
QGroupBox::title {{
    subcontrol-origin: margin;
    left: {SPACING['md']}px;
    padding: 0 {SPACING['xs']}px;
    color: {p['text_secondary']};
}}

/* ---- menus, tooltips, status ---- */
QMenu {{
    background-color: {p['menu_bg']};
    border: 1px solid {p['border_strong']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['xs']}px;
    color: {p['text']};
    font-size: {TYPE['body'][0]}px;
}}
QMenu::item {{
    padding: {SPACING['sm']}px {SPACING['md']}px;
    background: transparent;
    border-radius: {RADIUS['sm']}px;
    color: {p['text']};
}}
QMenu::item:selected {{ background: {p['accent_bg_strong']}; color: {p['text']}; }}
QMenu::item:disabled {{ color: {p['text_disabled']}; }}
QMenu::separator {{
    height: 1px;
    background: {p['border']};
    margin: {SPACING['xs']}px 0;
}}
QToolTip {{
    background-color: {p['tooltip_bg']};
    color: {p['text']};
    border: 1px solid {p['accent_border']};
    border-radius: {RADIUS['md']}px;
    padding: 5px 10px;
    font-size: {TYPE['secondary'][0]}px;
}}
QStatusBar {{
    background: {p['surface']};
    color: {p['text_secondary']};
    border-top: 1px solid {p['border']};
    font-size: {TYPE['micro'][0]}px;
}}
QStatusBar::item {{ border: none; }}

/* ---- shell v3 app bar (top-nav-shell 2.1) ---- */
QFrame#appBar {{
    background: {p['surface']};
    border-bottom: 1px solid {p['border']};
}}
QPushButton#brandMark {{
    background: transparent;
    border: none;
    border-radius: {RADIUS['md']}px;
    padding: 2px 4px;
}}
QPushButton#brandMark:hover {{ background: {p['surface_hover']}; }}
QPushButton#brandMark[pulse="true"] {{ background: {p['accent_bg']}; }}
QLabel#brandWordmark {{
    color: {p['text']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['title'][0]}px;
    font-weight: 600;
    background: transparent;
}}
QPushButton#saveStateChip {{
    background: {p['surface_raised']};
    color: {p['text_secondary']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: 3px 6px;
}}
QPushButton#saveStateChip:hover {{ border-color: {p['accent_border']}; color: {p['text']}; }}
QPushButton#saveStateChip[state="loaded"], QPushButton#saveStateChip[state="dirty"] {{ color: {p['text']}; }}
QPushButton#saveStateChip[state="dirty"] {{ border-color: {p['warning_border']}; }}
QPushButton#saveStateChip[state="error"] {{ border-color: {p['danger_border']}; }}
QPushButton#saveStateChip[pulse="true"] {{ border-color: {p['accent']}; color: {p['accent']}; }}
QLabel#saveChipText {{
    color: inherit;
    font-size: {TYPE['micro'][0]}px;
    font-weight: 600;
    background: transparent;
}}
QLabel#saveChipDirtyDot {{
    background: {p['warning']};
    border-radius: 3px;
}}
QPushButton#contextIndicator {{
    background: transparent;
    color: {p['text_secondary']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: 1px 6px;
}}
QPushButton#contextIndicator:hover {{ background: {p['surface_hover']}; color: {p['text']}; }}
QLabel#contextRow {{
    color: {p['text_secondary']};
    font-size: {TYPE['micro'][0]}px;
    background: transparent;
}}
QPushButton#appBarUtility {{
    background: transparent;
    border: none;
    border-radius: {RADIUS['sm']}px;
    padding: 3px;
}}
QPushButton#appBarUtility:hover {{ background: {p['surface_hover']}; }}
QPushButton#appBarUtility:checked {{ background: {p['surface_active']}; }}
QPushButton#appBarWarnBtn {{
    background: {p['warning_bg']};
    border: 1px solid {p['warning_border']};
}}
QPushButton#windowControlBtn {{
    background: transparent;
    border: none;
    border-radius: {RADIUS['sm']}px;
    padding: 2px;
}}
QPushButton#windowControlBtn:hover {{ background: {p['surface_hover']}; }}
QPushButton#windowControlBtn[danger="true"]:hover {{ background: {p['danger_bg']}; }}
QSplitter::handle:horizontal {{
    background: {p['border']};
    width: 2px;
}}
QSplitter::handle:horizontal:hover {{ background: {p['accent_border']}; width: 4px; }}
QSplitter::handle:vertical {{
    background: {p['border']};
    height: 2px;
}}
QSplitter::handle:vertical:hover {{ background: {p['accent_border']}; height: 4px; }}

/* ---- scrollbars ---- */
QScrollBar:vertical, QScrollBar:horizontal {{
    background: transparent;
    width: 10px;
    height: 10px;
    margin: 0;
    border-radius: 5px;
}}
QScrollBar::handle:vertical, QScrollBar::handle:horizontal {{
    background: {p['border_strong']};
    min-height: 24px;
    min-width: 24px;
    border-radius: 5px;
}}
QScrollBar::handle:vertical:hover, QScrollBar::handle:horizontal:hover {{
    background: {p['text_disabled']};
}}
QScrollBar::handle:vertical:pressed, QScrollBar::handle:horizontal:pressed {{
    background: {p['accent_border']};
}}
QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical,
QScrollBar::add-line:horizontal, QScrollBar::sub-line:horizontal {{
    height: 0; width: 0; background: none; border: none;
}}
QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical,
QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal {{ background: none; }}

/* ---- tabs ---- */
QTabWidget::pane {{
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['md']}px;
    margin-top: -1px;
}}
QTabBar {{ background: transparent; }}
QTabBar::tab {{
    background: transparent;
    border: none;
    border-bottom: 2px solid transparent;
    padding: {SPACING['sm'] + 1}px {SPACING['lg']}px;
    margin-right: {SPACING['xs']}px;
    color: {p['text_secondary']};
    font-weight: 600;
    font-size: {TYPE['secondary'][0]}px;
}}
QTabBar::tab:selected {{
    color: {p['accent']};
    border-bottom: 2px solid {p['accent']};
}}
QTabBar::tab:hover:!selected {{
    color: {p['text']};
    background: {p['surface_hover']};
    border-radius: {RADIUS['sm']}px {RADIUS['sm']}px 0 0;
}}
QTabBar::close-button {{ image: none; subcontrol-position: right; }}

/* ---- dialogs & system surfaces (022 sheet grammar) ---- */
QDialog {{
    background-color: {p['surface_raised']};
    color: {p['text']};
    border: 1px solid {p['border_strong']};
}}
QLabel#dialogKicker {{
    color: {p['text_disabled']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['micro'][0]}px;
    font-weight: 600;
    letter-spacing: 2px;
}}
QLabel#dialogTitle {{
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['title'][0]}px;
    font-weight: {TYPE['title'][1]};
    color: {p['text']};
}}
QMessageBox, QInputDialog {{
    background-color: {p['surface_raised']};
    color: {p['text']};
}}
QMessageBox QLabel, QInputDialog QLabel {{ color: {p['text']}; }}
QMessageBox QPushButton, QInputDialog QPushButton {{
    background-color: {p['surface_raised']};
    color: {p['text']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: 5px 14px;
    min-width: 72px;
    font-weight: 600;
}}
QMessageBox QPushButton:hover, QInputDialog QPushButton:hover {{
    background-color: {p['surface_hover']};
    border-color: {p['border_strong']};
}}
QFileDialog {{
    background-color: {p['canvas']};
    color: {p['text']};
}}
QFileDialog QLabel {{ color: {p['text_secondary']}; }}
QFileDialog QLineEdit {{
    background-color: {p['surface_input']};
    color: {p['text']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    padding: 5px 8px;
}}
QFileDialog QTreeView {{
    background: {p['surface']};
    color: {p['text']};
    border: 1px solid {p['border']};
}}
QFileDialog QComboBox {{
    background-color: {p['surface_input']};
    color: {p['text']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    padding: 4px 8px;
}}
QListView {{ background: transparent; }}
QColumnView {{ background: transparent; }}
QTextBrowser {{ background: transparent; color: {p['text']}; }}

/* ---- shared component classes (ui/chrome/components.py sets these) ---- */
QFrame[class="panel"] {{
    background-color: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['lg']}px;
}}
QFrame[class="card"] {{
    background-color: {p['surface_raised']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['lg']}px;
}}
QFrame[class="card"][selected="true"] {{
    border-color: {p['accent_border']};
    background-color: {p['accent_bg']};
}}
QFrame[class="divider"] {{ background: {p['border']}; max-height: 1px; border: none; }}
QFrame[class="divider"][vertical="true"] {{ max-height: none; max-width: 1px; }}

QLabel[class="display"] {{
    font-size: {d[0]}px; font-weight: {d[1]}; color: {p['text']};
    letter-spacing: -0.01em;
}}
QLabel[class="title"] {{
    font-size: {TYPE['title'][0]}px; font-weight: {TYPE['title'][1]}; color: {p['text']};
}}
QLabel[class="section"] {{
    font-size: {TYPE['section'][0]}px; font-weight: {TYPE['section'][1]};
    color: {p['text']};
}}
QLabel[class="secondary"] {{ color: {p['text_secondary']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel[class="micro"] {{ color: {p['text_secondary']}; font-size: {TYPE['micro'][0]}px; }}
QLabel[class="mono"] {{ font-family: {fonts.font_family_qss(fonts.FONT_MONO_STACK)}; }}

QLabel[badge="neutral"] {{
    background: {p['surface_raised']}; color: {p['text_secondary']};
    border: 1px solid {p['border']}; border-radius: 9px;
    padding: 1px 8px; font-size: {TYPE['micro'][0]}px; font-weight: 600;
}}
QLabel[badge="success"] {{
    background: {p['success_bg']}; color: {p['success']};
    border: 1px solid {p['success_border']}; border-radius: 9px;
    padding: 1px 8px; font-size: {TYPE['micro'][0]}px; font-weight: 600;
}}
QLabel[badge="warning"] {{
    background: {p['warning_bg']}; color: {p['warning']};
    border: 1px solid {p['warning_border']}; border-radius: 9px;
    padding: 1px 8px; font-size: {TYPE['micro'][0]}px; font-weight: 600;
}}
QLabel[badge="danger"] {{
    background: {p['danger_bg']}; color: {p['danger']};
    border: 1px solid {p['danger_border']}; border-radius: 9px;
    padding: 1px 8px; font-size: {TYPE['micro'][0]}px; font-weight: 600;
}}
QLabel[badge="info"] {{
    background: {p['info_bg']}; color: {p['info']};
    border: 1px solid {p['info_border']}; border-radius: 9px;
    padding: 1px 8px; font-size: {TYPE['micro'][0]}px; font-weight: 600;
}}
QLabel[badge="special"] {{
    background: {p['special_bg']}; color: {p['special']};
    border: 1px solid {p['special_border']}; border-radius: 9px;
    padding: 1px 8px; font-size: {TYPE['micro'][0]}px; font-weight: 600;
}}
QLabel[badge="accent"] {{
    background: {p['accent_bg']}; color: {p['accent']};
    border: 1px solid {p['accent_border']}; border-radius: 9px;
    padding: 1px 8px; font-size: {TYPE['micro'][0]}px; font-weight: 600;
}}

QLabel[class="dot"][level="success"] {{ background: {p['success']}; }}
QLabel[class="dot"][level="warning"] {{ background: {p['warning']}; }}
QLabel[class="dot"][level="danger"] {{ background: {p['danger']}; }}
QLabel[class="dot"][level="info"] {{ background: {p['info']}; }}
QLabel[class="dot"][level="special"] {{ background: {p['special']}; }}
QLabel[class="dot"][level="neutral"] {{ background: {p['text_disabled']}; }}
QLabel[class="dot"][level="accent"] {{ background: {p['accent']}; }}

QFrame[class="errorBanner"] {{
    background: {p['danger_bg']};
    border: 1px solid {p['danger_border']};
    border-radius: {RADIUS['md']}px;
}}
QFrame[class="errorBanner"] QLabel {{ color: {p['danger']}; }}

QFrame[class="toast"][toast_level="success"] {{
    background: {p['success_bg']}; border: 1px solid {p['success_border']}; border-radius: {RADIUS['sm']}px;
}}
QFrame[class="toast"][toast_level="warning"] {{
    background: {p['warning_bg']}; border: 1px solid {p['warning_border']}; border-radius: {RADIUS['sm']}px;
}}
QFrame[class="toast"][toast_level="danger"] {{
    background: {p['danger_bg']}; border: 1px solid {p['danger_border']}; border-radius: {RADIUS['sm']}px;
}}
QFrame[class="toast"][toast_level="info"] {{
    background: {p['info_bg']}; border: 1px solid {p['info_border']}; border-radius: {RADIUS['sm']}px;
}}
QFrame[class="toast"] QLabel {{ font-size: {TYPE['secondary'][0]}px; font-weight: 600; }}
QFrame[class="toast"][toast_level="success"] QLabel {{ color: {p['success']}; }}
QFrame[class="toast"][toast_level="warning"] QLabel {{ color: {p['warning']}; }}
QFrame[class="toast"][toast_level="danger"] QLabel {{ color: {p['danger']}; }}
QFrame[class="toast"][toast_level="info"] QLabel {{ color: {p['info']}; }}

QFrame[class="searchField"] {{
    background: {p['surface_input']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
}}
QFrame[class="searchField"] QLineEdit {{
    background: transparent; border: none; padding: 2px 0;
}}
QFrame[class="searchField"] QLineEdit:focus {{ border: none; }}
QFrame[class="searchField"] QLabel {{ color: {p['text_secondary']}; }}

/* ---- application shell chrome v2: NexusBand rail (plan 020) ---- */
QWidget#nexusBand {{
    background-color: {p['canvas']};
    border-left: 1px solid {p['border']};
}}
QWidget#bandMiddle {{ background: transparent; }}
QFrame#bandZoneRule {{
    background: {p['border']};
    border: none;
    margin: 3px 10px;
}}
QLabel#bandZoneCaption {{
    color: {p['text_disabled']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: 9px;
    font-weight: 600;
    letter-spacing: 1px;
    background: transparent;
    padding: 4px 2px 1px 2px;
}}
QPushButton[bandItem="true"] {{
    background: transparent;
    color: {p['text_secondary']};
    border: none;
    border-radius: {RADIUS['sm']}px;
    text-align: center;
    padding: 0px;
}}
QPushButton[bandItem="true"]:hover {{
    background: {p['surface_hover']};
    color: {p['text']};
}}
QPushButton[bandItem="true"]:focus {{
    border: 1px solid {p['accent_border']};
}}
QPushButton[bandItem="true"][active="true"] {{
    color: {p['accent']};
    background: {p['accent_bg']};
    font-weight: 600;
}}
QPushButton[bandItem="true"][active="true"]:hover {{
    background: {p['accent_bg_strong']};
    color: {p['accent_hover']};
}}
QPushButton[bandItem="true"]:disabled {{
    color: {p['text_disabled']};
    background: transparent;
}}
QPushButton[bandUtility="true"] {{
    background: transparent;
    color: {p['text_secondary']};
    border: none;
    border-radius: {RADIUS['sm']}px;
}}
QPushButton[bandUtility="true"]:hover {{
    background: {p['surface_hover']};
    color: {p['text']};
}}
QPushButton[bandUtility="true"]:pressed {{ background: {p['surface_active']}; }}
QPushButton[bandUtility="true"]:focus {{ border: 1px solid {p['accent_border']}; }}
QPushButton[bandUtility="true"]:disabled {{ color: {p['text_disabled']}; }}
QPushButton[bandUtility="true"][active="true"] {{
    color: {p['accent']};
    background: {p['accent_bg']};
}}
QPushButton#bandMasthead {{
    color: {p['text_secondary']};
    font-size: 15px;
}}
QPushButton#bandMasthead[pulse="true"] {{
    color: {p['warning']};
    background: {p['warning_bg']};
}}
QLabel#bandDirtyDot {{
    background: {p['accent']};
    border-radius: 4px;
}}

/* ---- InstrumentTray (plan 020 §4.2) ---- */
QWidget#instrumentTray {{ background: transparent; }}
QPushButton#trayStateRow {{
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    margin: 0 6px;
    text-align: left;
}}
QPushButton#trayStateRow:hover {{ border-color: {p['border_strong']}; background: {p['surface_raised']}; }}
QPushButton#trayStateRow:focus {{ border-color: {p['accent_border']}; }}
QPushButton#trayStateRow[state="loaded"] {{
    background: {p['success_bg']};
    border-color: {p['success_border']};
}}
QPushButton#trayStateRow[state="dirty"] {{
    background: {p['warning_bg']};
    border-color: {p['warning_border']};
}}
QPushButton#trayStateRow[state="error"] {{
    background: {p['danger_bg']};
    border-color: {p['danger_border']};
}}
QPushButton#trayStateRow[state="loading"], QPushButton#trayStateRow[state="saving"] {{
    background: {p['info_bg']};
    border-color: {p['info_border']};
}}
QLabel#trayStateIcon {{
    background: transparent; border: none;
    font-family: {font_family_qss(FONT_ICON_STACK)};
    font-size: 11px;
}}
QLabel#trayStateIcon[state="loaded"] {{ color: {p['success']}; }}
QLabel#trayStateIcon[state="dirty"] {{ color: {p['warning']}; }}
QLabel#trayStateIcon[state="error"] {{ color: {p['danger']}; }}
QLabel#trayStateIcon[state="loading"], QLabel#trayStateIcon[state="saving"] {{ color: {p['info']}; }}
QLabel#trayStateText {{
    background: transparent; border: none;
    color: {p['text_secondary']};
    font-size: {TYPE['micro'][0]}px;
}}
QLabel#traySection {{
    color: {p['text_disabled']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['micro'][0]}px;
    font-weight: 600;
    letter-spacing: 1px;
    padding: 3px 8px 1px 8px;
}}
QLabel#trayLabel {{
    color: {p['text_disabled']};
    font-size: {TYPE['micro'][0]}px;
}}
QLabel#trayValue {{
    color: {p['text']};
    font-size: {TYPE['micro'][0]}px;
    font-weight: 600;
}}
QLabel#trayValue[placeholder="true"] {{ color: {p['text_disabled']}; font-weight: 400; }}
QLabel#trayMetricValue {{
    color: {p['text']};
    font-family: {font_family_qss(FONT_MONO_STACK)};
    font-size: {TYPE['micro'][0]}px;
    font-weight: 600;
}}
QLabel#trayMetricValue[placeholder="true"] {{ color: {p['text_disabled']}; font-weight: 400; }}
QPushButton#trayExpandBtn {{
    background: transparent;
    border: none;
    border-radius: {RADIUS['sm']}px;
    color: {p['text_secondary']};
    font-size: {TYPE['micro'][0]}px;
}}
QPushButton#trayExpandBtn:hover {{ background: {p['surface_hover']}; color: {p['text']}; }}
QPushButton#trayExpandBtn:focus {{ border: 1px solid {p['accent_border']}; }}

/* ---- TrayDrawer overlay (canvas-local, plan 020 §4.2) ---- */
QFrame#trayDrawer {{
    background: {p['surface_raised']};
    border: 1px solid {p['border_strong']};
    border-radius: {RADIUS['lg']}px;
}}
QLabel#drawerTitle {{
    color: {p['text']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['title'][0]}px;
    font-weight: {TYPE['title'][1]};
}}
QPushButton#drawerCloseBtn {{
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    color: {p['text_secondary']};
    font-family: {font_family_qss(FONT_ICON_STACK)};
}}
QPushButton#drawerCloseBtn:hover {{ background: {p['danger_bg']}; color: {p['danger']}; border-color: {p['danger_border']}; }}

/* ---- page ribbon (plan 020 §4.4) ---- */
QFrame#pageRibbon {{
    background: transparent;
    border: none;
    border-bottom: 1px solid {p['border']};
}}
QLabel#ribbonTitle {{
    color: {p['text']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['display'][0]}px;
    font-weight: {TYPE['display'][1]};
}}
QLabel#ribbonZone {{
    color: {p['text_disabled']};
    font-size: {TYPE['micro'][0]}px;
    letter-spacing: 1px;
    font-weight: 600;
}}
QLabel#ribbonSep {{
    color: {p['text_disabled']};
    font-size: {TYPE['micro'][0]}px;
}}

/* ---- transitional: legacy sidebar/header blocks (removed in plan 025) ---- */
QWidget#sideBar {{
    background-color: {p['canvas']};
    border-right: 1px solid {p['border']};
}}
QLabel#sidebarSection {{
    color: {p['text_disabled']};
    font-size: {TYPE['micro'][0]}px;
    font-weight: 600;
    letter-spacing: 1px;
    padding: {SPACING['sm']}px {SPACING['md']}px {SPACING['xs']}px;
}}
QPushButton[sidebarItem="true"] {{
    background: transparent;
    color: {p['text_secondary']};
    border: none;
    border-radius: {RADIUS['md']}px;
    font-size: 14px;
    text-align: center;
    padding: 0px;
}}
QPushButton[sidebarItem="true"]:hover {{
    background: {p['surface_hover']};
    color: {p['text']};
}}
QPushButton[sidebarItem="true"]:focus {{
    border: 1px solid {p['accent_border']};
}}
QPushButton[sidebarItem="true"][active="true"] {{
    color: {p['accent']};
    background: {p['accent_bg']};
}}
QPushButton[sidebarItem="true"][active="true"]:hover {{
    background: {p['accent_bg_strong']};
    color: {p['accent_hover']};
}}
QPushButton[sidebarItem="true"]:disabled {{
    color: {p['text_disabled']};
    background: transparent;
}}

/* header chips: neutral by default, semantic only where meaning exists */
QPushButton#menuChip, QLabel#versionChip, QLabel#gameVersionChip {{
    background: {p['surface_raised']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['pill']}px;
    padding: {SPACING['xs']}px {SPACING['md'] - 2}px;
    color: {p['text_secondary']};
}}
QPushButton#menuChip:hover {{
    background: {p['surface_hover']};
    border-color: {p['border_strong']};
    color: {p['text']};
}}
QPushButton#menuChip:pressed {{ background: {p['surface_active']}; }}
QPushButton#menuChip:disabled {{ color: {p['text_disabled']}; background: {p['surface']}; }}
QLabel#versionChip[pulse="true"] {{
    background: {p['warning_bg']};
    border-color: {p['warning_border']};
    color: {p['warning']};
}}
QPushButton#controlChip {{
    background: transparent;
    border: 1px solid transparent;
    border-radius: {RADIUS['md']}px;
    color: {p['text_secondary']};
    text-align: center;
}}
QPushButton#controlChip:hover {{
    background: {p['surface_hover']};
    color: {p['text']};
}}
QPushButton#controlChip:pressed {{ background: {p['surface_active']}; }}
QPushButton#controlChip:disabled {{ color: {p['text_disabled']}; }}
QPushButton#controlChip[role="close"] {{ color: {p['text_secondary']}; }}
QPushButton#controlChip[role="close"]:hover {{
    background: {p['danger_bg']};
    border-color: {p['danger_border']};
    color: {p['danger']};
}}

/* header action buttons: one tool-chip style; warn/save carry semantics */
QPushButton#hdrBtn, QPushButton#infoBtn, QPushButton#warnBtn, QPushButton#saveBtn {{
    background: transparent;
    border: 1px solid transparent;
    border-radius: {RADIUS['md']}px;
    color: {p['text_secondary']};
    text-align: center;
}}
QPushButton#hdrBtn:hover, QPushButton#infoBtn:hover {{
    background: {p['surface_hover']};
    color: {p['text']};
}}
QPushButton#hdrBtn:pressed, QPushButton#infoBtn:pressed {{ background: {p['surface_active']}; }}
QPushButton#hdrBtn:disabled, QPushButton#infoBtn:disabled, QPushButton#saveBtn:disabled {{
    color: {p['text_disabled']};
}}
QPushButton#warnBtn {{
    background: {p['warning_bg']};
    border-color: {p['warning_border']};
    color: {p['warning']};
}}
QPushButton#warnBtn:hover {{ background: {p['warning_bg']}; border-color: {p['warning']}; color: {p['text']}; }}
QPushButton#warnBtn:pressed {{ background: {p['warning_border']}; }}
QPushButton#saveBtn {{
    background: {p['accent_bg']};
    border-color: {p['accent_border']};
    color: {p['accent']};
}}
QPushButton#saveBtn:hover {{ background: {p['accent_bg_strong']}; border-color: {p['accent_border_strong']}; color: {p['text']}; }}
QPushButton#saveBtn:pressed {{ background: {p['accent_border']}; }}
QPushButton#saveBtn[dirty="true"] {{
    background: {p['success_bg']};
    border-color: {p['success_border']};
    color: {p['success']};
}}
QPushButton#saveBtn[dirty="true"]:hover {{ background: {p['success_bg']}; border-color: {p['success']}; color: {p['text']}; }}
QPushButton#discordChip {{
    background: transparent;
    border: 1px solid transparent;
    border-radius: {RADIUS['md']}px;
    color: {p['info']};
}}
QPushButton#discordChip:hover {{ background: {p['info_bg']}; border-color: {p['info_border']}; }}

/* detached console */
QFrame#mainContainer {{
    background: {p['surface']};
    border-radius: {RADIUS['lg']}px;
    border: 1px solid {p['border']};
}}
QTextEdit#consoleTextEdit {{
    background: {p['canvas']};
    color: {p['text_secondary']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['sm']}px;
    selection-background-color: {p['accent_bg_strong']};
    font-family: {fonts.font_family_qss(fonts.FONT_MONO_STACK)};
}}
QLabel#consoleTitleLabel {{
    font-weight: bold;
    font-size: 14px;
    color: {p['text']};
    background: transparent;
}}
QPushButton#consoleCloseBtn {{
    background: transparent;
    color: {p['text_secondary']};
    font-size: 14px;
    font-weight: bold;
    border: none;
    padding: 5px;
}}
QPushButton#consoleCloseBtn:hover {{
    background: {p['danger_bg']};
    border-radius: {RADIUS['sm']}px;
    color: {p['danger']};
}}
QPushButton#detachButton, QPushButton#attachButton {{
    background: {p['surface_raised']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['xs']}px {SPACING['sm']}px;
    color: {p['text_secondary']};
}}
QPushButton#detachButton:hover, QPushButton#attachButton:hover {{
    background: {p['surface_hover']};
    border-color: {p['border_strong']};
    color: {p['text']};
}}
QPushButton#detachButton:pressed, QPushButton#attachButton:pressed {{ background: {p['surface_active']}; }}
QPushButton#collapseToggle {{
    background: {p['surface_raised']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    color: {p['text_secondary']};
}}
QPushButton#collapseToggle:hover {{
    background: {p['surface_hover']};
    border-color: {p['border_strong']};
    color: {p['text']};
}}
QPushButton#collapseToggle:pressed {{ background: {p['surface_active']}; }}

/* results dock */
QWidget#resultsWidget {{ background: transparent; }}
QPushButton#resultsCloseBtn {{
    background: {p['surface_raised']};
    color: {p['text_secondary']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    font-size: 13px;
    font-weight: 600;
    padding: 0;
}}
QPushButton#resultsCloseBtn:hover {{
    background: {p['danger_bg']};
    border-color: {p['danger_border']};
    color: {p['danger']};
}}
QPushButton#resultsCloseBtn:pressed {{ background: {p['danger_border']}; }}
QPushButton#copyStatsBtn {{
    background: transparent;
    border: none;
    font-size: 14px;
    color: {p['text_secondary']};
    padding: 2px;
}}
QPushButton#copyStatsBtn:hover {{
    background: {p['surface_hover']};
    border-radius: {RADIUS['sm']}px;
    color: {p['text']};
}}
QLabel#statsHeaderLabel {{ color: {p['text']}; font-weight: 700; }}
QLabel#statsFieldLabel {{ color: {p['text_secondary']}; }}
QLabel#statsValueLabel {{ color: {p['text']}; font-weight: 700; }}
QLabel#statsValueLabel[placeholder="true"] {{ color: {p['text_disabled']}; font-weight: 400; }}

/* ---- search screens ---- */
QLineEdit#searchInput {{
    background: {p['surface_input']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: 4px 10px;
    color: {p['text']};
    font-size: {TYPE['secondary'][0]}px;
    min-height: {HEIGHT['compact'] + 4}px;
}}
QLineEdit#searchInput:focus {{ border-color: {p['accent_border_strong']}; }}
QFrame#bulkActionBar {{
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['sm']}px;
}}
QLabel#bulkActionLabel {{ font-weight: 600; color: {p['text_secondary']}; }}
QLabel#bulkHintLabel {{ color: {p['text_secondary']}; font-size: {TYPE['secondary'][0]}px; }}
QLabel#searchCount {{
    color: {p['text_disabled']};
    font-family: {font_family_qss(FONT_MONO_STACK)};
    font-size: {TYPE['micro'][0]}px;
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['pill']}px;
    padding: 1px 8px;
}}
QFrame#tableFooter {{
    background: {p['surface']};
    border: none;
    border-top: 1px solid {p['border']};
}}
QPushButton#pageSwitchBtn {{
    background: transparent;
    border: 1px solid {p['border']};
    border-radius: {RADIUS['pill']}px;
    color: {p['text_secondary']};
    padding: {SPACING['xs']}px {SPACING['md']}px;
    font-size: {TYPE['secondary'][0]}px;
}}
QPushButton#pageSwitchBtn:hover {{ background: {p['surface_hover']}; color: {p['text']}; }}
QPushButton#pageSwitchBtn:checked {{
    background: {p['accent_bg']};
    border-color: {p['accent_border']};
    color: {p['accent']};
    font-weight: 600;
}}
QPushButton#pageSwitchBtn:focus {{ border-color: {p['accent_border_strong']}; }}
QPushButton#ghostBtn, QPushButton#toolButton {{
    background: transparent;
    border: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    color: {p['text_secondary']};
    padding: {SPACING['xs']}px {SPACING['md']}px;
    font-size: {TYPE['secondary'][0]}px;
}}
QPushButton#ghostBtn:hover, QPushButton#toolButton:hover {{
    background: {p['surface_hover']};
    color: {p['text']};
    border-color: {p['border_strong']};
}}
QPushButton#ghostBtn:pressed, QPushButton#toolButton:pressed {{ background: {p['surface_active']}; }}
QPushButton#ghostBtn:disabled, QPushButton#toolButton:disabled {{ color: {p['text_disabled']}; }}
QTreeWidget#jsonTree {{
    background: {p['canvas']};
    alternate-background-color: {p['surface']};
    border: none;
    border-top: 1px solid {p['border']};
}}
/* Map viewer: floating legend card over the canvas (008-r02) */
QWidget#mapLegendCard {{
    background: {p['surface_raised']};
    border: 1px solid {p['border_strong']};
    border-radius: {RADIUS['md']}px;
}}
QLabel#saveStateChip {{
    background: {p['surface_raised']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['pill']}px;
    padding: {SPACING['xs'] + 1}px {SPACING['sm'] + 2}px;
    color: {p['text_disabled']};
}}
QLabel#saveStateChip[state="loading"] {{ color: {p['info']}; border-color: {p['info_border']}; background: {p['info_bg']}; }}
QLabel#saveStateChip[state="loaded"] {{ color: {p['success']}; border-color: {p['success_border']}; background: {p['success_bg']}; }}
QLabel#saveStateChip[state="dirty"] {{ color: {p['warning']}; border-color: {p['warning_border']}; background: {p['warning_bg']}; }}
QLabel#saveStateChip[state="saving"] {{ color: {p['info']}; border-color: {p['info_border']}; background: {p['info_bg']}; }}
QLabel#saveStateChip[state="error"] {{ color: {p['danger']}; border-color: {p['danger_border']}; background: {p['danger_bg']}; }}

/* ---- Start page v2 (plan 021): masthead + field report + campaign + missions ---- */
QWidget#startCanvas {{ background: transparent; }}
QFrame#opsMasthead {{
    background: transparent;
    border: none;
    border-bottom: 1px solid {p['border']};
    padding-bottom: {SPACING['md']}px;
}}
QLabel#opsKicker {{
    color: {p['text_disabled']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['micro'][0]}px;
    font-weight: 600;
    letter-spacing: 2px;
}}
QLabel#opsWorldName {{
    color: {p['text']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['title'][0]}px;
    font-weight: {TYPE['title'][1]};
}}
QLabel#opsWorldName[state="loaded"] {{ color: {p['success']}; }}
QLabel#opsStateDot {{
    background: {p['text_disabled']};
    border-radius: 5px;
}}
QLabel#opsStateDot[state="loaded"] {{ background: {p['success']}; }}
QLabel#opsStateDot[state="no_save"] {{ background: {p['text_disabled']}; }}
QPushButton#opsLoadBtn {{
    background: {p['accent']};
    border: 1px solid {p['accent']};
    border-radius: {RADIUS['md']}px;
    color: {p['text_on_accent']};
    font-weight: 700;
    padding: {SPACING['sm']}px {SPACING['lg']}px;
}}
QPushButton#opsLoadBtn:hover {{ background: {p['accent_hover']}; border-color: {p['accent_hover']}; }}
QPushButton#opsLoadBtn:pressed {{ background: {p['accent_pressed']}; }}
QPushButton#opsLoadBtn[loadKind="secondary"] {{
    background: {p['surface_raised']};
    border: 1px solid {p['border_strong']};
    color: {p['text']};
}}
QPushButton#opsLoadBtn[loadKind="secondary"]:hover {{
    background: {p['surface_hover']};
    border-color: {p['accent_border']};
    color: {p['accent']};
}}
QPushButton#opsSavePath {{
    background: transparent;
    color: {p['text_secondary']};
    border: none;
    border-radius: {RADIUS['sm']}px;
    padding: 2px 0px;
    text-align: left;
    font-size: {TYPE['secondary'][0]}px;
    font-family: {font_family_qss(FONT_MONO_STACK)};
}}
QPushButton#opsSavePath:hover {{ color: {p['accent']}; }}
QLabel#opsDropHint {{ color: {p['text_disabled']}; font-size: {TYPE['micro'][0]}px; }}
QFrame#fieldReport {{
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
}}
QWidget#fieldMetric {{ background: transparent; border-radius: {RADIUS['sm']}px; }}
QWidget#fieldMetric:hover {{ background: {p['surface_hover']}; }}
QLabel#fieldMetricValue {{
    color: {p['text']};
    font-family: {font_family_qss(FONT_MONO_STACK)};
    font-size: 15px;
    font-weight: 600;
}}
QLabel#fieldMetricValue[placeholder="true"] {{ color: {p['text_disabled']}; font-weight: 400; }}
QFrame#campaignStrip {{
    background: transparent;
    border: none;
    border-top: 1px solid {p['border']};
    border-bottom: 1px solid {p['border']};
}}
QPushButton#campaignStep {{
    background: transparent;
    border: none;
    border-radius: {RADIUS['sm']}px;
    color: {p['text_secondary']};
    padding: {SPACING['sm'] - 2}px {SPACING['md']}px;
    font-size: {TYPE['body'][0]}px;
    font-weight: 600;
}}
QPushButton#campaignStep:hover {{ background: {p['surface_hover']}; color: {p['accent']}; }}
QPushButton#campaignStep:pressed {{ background: {p['surface_active']}; }}
QPushButton#campaignStep:focus {{ border: 1px solid {p['accent_border']}; }}
QWidget#missionColumn {{ background: transparent; }}
QLabel#missionZone {{
    color: {p['text_disabled']};
    font-family: {font_family_qss(FONT_HEADING_STACK)};
    font-size: {TYPE['section'][0]}px;
    font-weight: {TYPE['section'][1]};
    letter-spacing: 1px;
    padding: {SPACING['xs']}px 0;
}}
QPushButton#missionRow {{
    background: transparent;
    border: none;
    border-bottom: 1px solid {p['border']};
    border-radius: {RADIUS['sm']}px;
    color: {p['text']};
    text-align: left;
    padding: {SPACING['sm'] + 2}px {SPACING['md']}px;
    font-size: {TYPE['body'][0]}px;
}}
QPushButton#missionRow:hover {{
    background: {p['surface_hover']};
    color: {p['accent']};
}}
QPushButton#missionRow:pressed {{ background: {p['surface_active']}; color: {p['accent_pressed']}; }}
QPushButton#missionRow:focus {{ border: 1px solid {p['accent_border']}; }}

QPushButton#dialogOption {{
    background: {p['surface_raised']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['sm']}px {SPACING['md']}px;
    color: {p['text']};
    text-align: left;
    padding-left: {SPACING['lg']}px;
}}
QPushButton#dialogOption:hover {{ background: {p['surface_hover']}; border-color: {p['accent_border']}; }}
QPushButton#dialogOption:pressed {{ background: {p['surface_active']}; }}
QPushButton#dialogCancel {{
    background: transparent;
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['sm']}px {SPACING['xl']}px;
    color: {p['text_secondary']};
}}
QPushButton#dialogCancel:hover {{ background: {p['surface_hover']}; color: {p['text']}; }}
QFrame#valueCard {{
    background: {p['surface_raised']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
}}
QFrame#gradientSeparator {{ background: {p['border']}; max-height: 1px; border: none; }}
QWidget#statsGrid {{ background: transparent; }}
QLabel#statsField {{ color: {p['text_secondary']}; }}
QLabel#statsValue {{ color: {p['text']}; }}
QLabel#statsHeader {{ color: {p['text_secondary']}; font-size: {TYPE['micro'][0]}px; font-weight: 600; letter-spacing: 1px; }}
QLabel#sectionHeader {{ color: {p['text_secondary']}; font-size: {TYPE['micro'][0]}px; font-weight: 600; letter-spacing: 1px; }}
QFrame#glassPanel {{ background: {p['surface']}; border: 1px solid {p['border']}; border-radius: {RADIUS['lg']}px; }}

/* ---- ui-modernization Phase 0: promoted selectors (were inline or missing).
   Token/property selectors only. Dialogs that still carry inline copies of
   these rules keep rendering from their inline copy until their Phase 4
   migration; the builder copy is the target state. ---- */
QWidget#windowControls {{ background: transparent; border: none; }}
QPushButton#windowControlBtn {{
    background: transparent;
    border: 1px solid transparent;
    border-radius: {RADIUS['sm']}px;
    color: {p['text_secondary']};
    padding: 0px;
}}
QPushButton#windowControlBtn:hover {{
    background: {p['surface_hover']};
    color: {p['text']};
}}
QPushButton#windowControlBtn:pressed {{ background: {p['surface_active']}; }}
QPushButton#windowControlBtn:focus {{ border: 1px solid {p['accent_border']}; }}
QPushButton#windowControlBtn:disabled {{ color: {p['text_disabled']}; background: transparent; }}
QPushButton#windowControlBtn[danger="true"]:hover {{
    background: {p['danger_bg']};
    border-color: {p['danger_border']};
    color: {p['danger']};
}}
QPushButton#navBtn {{
    background: {p['accent_bg']};
    color: {p['accent']};
    border: 1px solid {p['accent_border']};
    border-radius: {RADIUS['md']}px;
    padding: {SPACING['sm'] - 2}px {SPACING['md'] - 2}px;
    font-weight: 600;
}}
QPushButton#navBtn:hover {{
    background: {p['accent_bg_strong']};
    border-color: {p['accent_border_strong']};
    color: {p['text']};
}}
QPushButton#navBtn:pressed {{ background: {p['accent_border']}; }}
QPushButton#navBtn:focus {{ border: 1px solid {p['text']}; }}
QPushButton#navBtn:disabled {{ color: {p['text_disabled']}; background: {p['surface']}; border-color: {p['border']}; }}
QFrame#passiveCard {{
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
}}
QFrame[tech_selected="false"] {{
    background: {p['surface']};
    border: 1px solid {p['border']};
    border-radius: {RADIUS['md']}px;
}}
QFrame[tech_selected="false"]:hover {{
    background: {p['surface_hover']};
    border-color: {p['accent_border']};
}}
QFrame[tech_selected="true"] {{
    background: {p['accent_bg_strong']};
    border: 1px solid {p['accent_border_strong']};
    border-radius: {RADIUS['md']}px;
}}
/* fix-illegal cards/rows: property-driven selection (Phase 4) */
QFrame[playerCard="true"] {{
    background: {p['surface']};
    border: 1px solid transparent;
    border-radius: {RADIUS['md']}px;
}}
QFrame[playerCard="true"]:hover {{
    background: {p['surface_hover']};
    border-color: {p['accent_border']};
}}
QFrame[playerCard="true"][selected="true"] {{
    background: {p['accent_bg_strong']};
    border: 1px solid {p['accent_border_strong']};
}}
QFrame[playerCard="true"][selected="true"]:hover {{
    background: {p['accent_bg_strong']};
    border-color: {p['accent']};
}}
QFrame[palRow="true"] {{
    background: {p['surface']};
    border-radius: {RADIUS['md']}px;
}}
QFrame[palRow="true"]:hover {{ background: {p['surface_hover']}; }}
/* transient skill-picker popup (Phase 4): floating card, global input/list rules inside */
QWidget#skillPicker {{
    background: {p['surface_raised']};
    border: 1px solid {p['border_strong']};
    border-radius: {RADIUS['lg']}px;
}}
"""
